version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    labels:
      - dependencies
      - rust
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: UTC
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(actions)"
